week_10/auction_site/config/routes.rb
Rails.application.routes.draw do

	devise_for :users

root to: "static_pages#home"


get '/' => 'users#home'

    resources :users, only: [:new, :show, :create, :destroy] do 
      resources :products, only: [:index, :show, :create, :destroy, :new]
    end


get '/products' => 'products#all', as: :products


post '/products/:product_id/bids' => 'bids#create', as: :product_bids


end

week_10/auction_site/app/models/bid.rb
class Bid < ActiveRecord::Base
  belongs_to :user
  belongs_to :product

  attr_reader :email

  validate :bid_cannot_be_lower_than_minimum_bid, :bid_cannot_be_lower_than_high_bid,
  		 	:owner_cannot_bid_on_products

  def bid_cannot_be_lower_than_minimum_bid
  	user = self.user
  	product = self.product
  	bids = product.bids.order(amount: :desc)
  	high_bid = bids.first

  	if (high_bid != nil) && (self.amount < product.minimum_bid)
  		errors.add(:bid, "cannot be lower than minimum bid")
 	end
  end

  def bid_cannot_be_lower_than_high_bid
  	bids = product.bids.order(amount: :desc)
  		high_bid = bids.first

  	if (high_bid != nil) && (self.amount < high_bid.amount)
  		errors.add(:bid, "cannot be lower than current high bid")
  	end
  end

  def owner_cannot_bid_on_products
  	if user.id == product.user.id
  		errors.add(:user, "can't bid on own products")
  	end
  end


end

week_10/auction_site/app/models/product.rb
class Product < ActiveRecord::Base
	has_many :bids
	belongs_to :user
end

week_10/auction_site/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :products
  has_many :bids
  validates :email, uniqueness: true, presence: true
  validates :name, presence: true
end

week_10/auction_site/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  	def after_sign_in_path_for(resource)
  		user_path(resource) 
	end

  protected
  	def configure_permitted_parameters
  		devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  	end
end

week_10/auction_site/app/controllers/bids_controller.rb
class BidsController < ApplicationController
	
	def create
		@bidder = User.find_by(email: params[:bid][:email])
		@product = Product.find_by(id: params[:product_id])
		
		@user = @product.user
		
		
		@bid = Bid.new(
			amount: params[:bid][:amount],
			user_id: @bidder.id,
			product_id: @product.id
			)

		@bids = @product.bids.order(amount: :desc)
		@high = @bids.first

		if @bid.save
			redirect_to user_product_path(@user, @product)
		else
			render 'products/show'
		end
	end

end

week_10/auction_site/app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def new
		@user = User.find(params[:user_id])
		@product = @user.products.new
	end

	def all
		@all_products = Product.all
	end

	def create
        @user = User.find params[:user_id]


        #permit is whitelisting only those attributes to be assigned
        product_params = params.require(:product).permit(:title, :minimum_bid, :description, :deadline)

        # without permit: @project.time_entries.new params[:time_entry]

        @product = @user.products.new(product_params)
        if @product.save
            redirect_to user_products_path(@user.id)
        else
            render 'new'
        end
 	end
	
 	def show
        @user = User.find(params[:user_id])
        @product = Product.find_by(id: params[:id])

        @bid = Bid.new
        @bids = @product.bids.order(amount: :desc)
        @high_bid = @bids.first

    end



	def index
		@user = User.find(params[:user_id])
		@products = @user.products.all
	end
end

week_10/auction_site/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
	end
end

week_10/auction_site/app/controllers/users_controller.rb
class UsersController < ApplicationController

	def home
	end

	def new
		@user = User.new
	end
	
	def show
		@user = User.find_by(id: params[:id])
	 end

	
end

week_10/auction_site/app/helpers/bids_helper.rb
module BidsHelper
end

week_10/auction_site/app/helpers/products_helper.rb
module ProductsHelper
end

week_10/auction_site/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

week_10/auction_site/app/views/products/all.html.erb
All Products:
<ul>
	<% @all_products.each do |product| %>
   		 <li><%= link_to(product.title, user_product_path(product.user.id, product)) %> </li>
    <% end %>
 </ul>

week_10/auction_site/app/views/products/index.html.erb
<h1><%= @user.name %> Products: </h1>
<ul>
<% @products.each do |product| %>
    <li><%= link_to(product.title, user_product_path(@user, product)) %> </li>
    <% end %>
    </ul>

<%= link_to "Back to Profile Page", user_path(@user) %><br>
<%= link_to "Create New Product", new_user_product_path %>

week_10/auction_site/app/views/products/new.html.erb
<% if @product.errors.any? %>
	<ul>
		<% @product.errors.full_messages.each do |error_msg| %>
			<li> <%= error_msg %> </li>
			<% end %>
			</ul>
			<% end %>



<h1> Enter New Product </h1>

<%= form_for [@user, @product] do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<br>
	<%= f.label :minimum_bid %>
	<%= f.number_field :minimum_bid %>
	<br>
	<%= f.label :description %>
	<%= f.text_field :description %>
	<br>
	<%= f.label :deadline %>
	<%= f.date_field :deadline %>
	<br>
	<%= f.submit "Add Product" %>

<% end %>

<%= link_to("View all products", user_products_path(@user)) %>

week_10/auction_site/app/views/products/show.html.erb
<% if @bid.errors.any? %>
	<ul>
		<% @bid.errors.full_messages.each do |error_msg| %>
			<li> <%= error_msg %> </li>
		<%end%>

	</ul>
	<% end %>

<h1>Thanks <%= @user.name %> for creating your new product: <%= @product.title %> </h1>  

<h2> Description: <%= @product.description %> </h2>
<h2> Minimum Bid: $<%= @product.minimum_bid %> </h2>
<h2> Deadline: <%= @product.deadline %> </h2>

<%= link_to("Create New Product", new_user_product_path(@user)) %> <br>
<%= link_to "Back to All Products", user_products_path(@user) %>

<br>
<br>


<% if Date.today < @product.deadline %>

		<% @bids.each do |bid| %>
			<li>
				$<%= bid.amount %> - <b> Bidder: </b>
				<%= bid.user.name %>
			</li>
		<% end %> <br>

			<%= form_for [@product, @bid] do |f| %>
				<%= f.label :amount %>
				<%= f.number_field :amount %>

				<br>
				<%= f.label :email %>
				<%= f.text_field :email %>
				<br>
				<br>
				<%= f.submit "Place Bid" %>

			<% end %>

<% else %>
		<% if @high_bid == nil %>
				<h1> no bids, bidding is over!</h1>
				<% else %>
			<%= @high_bid.amount %> - <b> Winning Bidder: </b> <%= @high_bid.user.name %>
		<%end%>
<%end%>

week_10/auction_site/app/views/static_pages/home.html.erb
<h1>Welcome to Auction Site</h1>


<%= link_to "Sign Up", new_user_registration_path%><br>
<%= link_to "Login", new_user_session_path%><br>

<%= link_to "Logout", destroy_user_session_path, method: :delete %>