week_9/ruby_on_rails Tues/timetracking/config/routes.rb
Rails.application.routes.draw do
  get '/' => 'site#home'
  get '/contact' => 'site#contact'

  resources :projects, only: [:index, :show, :new, :create] do 
    resources :time_entries, except: [:show] 
  end

  

end

week_9/ruby_on_rails Tues/timetracking/app/models/project.rb
class Project < ActiveRecord::Base
	has_many :time_entries
	# has_many :entry, class_name: "TimeEntry" if i wanted to call it something else than time_entries

	validates :name, presence: true, uniqueness: true, length: {maximum: 30}, format: {with: /[a-zA-Z0-9]/ }


	def self.clean_old
		where("created_at < ?", 1.week.ago).destroy_all
	end

	def self.last_created_projects(limit)
		limit(limit).order(created_at: :desc)
	end

	def total_hours_in_month(month, year)
		date = Time.new(year, month)
		entries_in_month = time_entries.where(date: date..date.end_of_month)

		hours = entries_in_month.sum { |e| e.hours }
		minutes = entries_in_month.sum { |e| e.minutes }
		hours + (minutes / 60)
	end
end


# # EXAMPLE
# class Project
# 	attr_reader :name

# 	def initialize(name)
# 		@name = name
# 	end 
# end
# p = Project.new("Ironhack")
# p.name

week_9/ruby_on_rails Tues/timetracking/app/models/time_entry.rb
class TimeEntry < ActiveRecord::Base
	belongs_to :project

	validates :project_id, presence: true
	validates :hours, :minute, presence: true, numericality: true
	validates :date, presence: true


end

week_9/ruby_on_rails Tues/timetracking/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
		@projects = Project.last_created_projects(10)
	end

	def new
		@project = Project.new
	end

	def create
		@project = Project.new(
			name: params[:project][:name],
			description: params[:project][:description]
			)
		@project.save
		redirect_to '/projects'
	end

	def show
		# begin
		# 	@project = Project.find(params[:id])
		# rescue ActiveRecord::RecordNotFound
		# 	# redirect_to '/projects'
		# 	render 'no_projects_found'
		# end
		
		@project = Project.find(params[:id])
		unless @project  #use unless if you dont have an else and if you dont have more than one condition
			render 'no_projects_found'
		end
	end

end

week_9/ruby_on_rails Tues/timetracking/app/controllers/site_controller.rb
class SiteController < ApplicationController
	def home #instance method for an action - in this case action being 'home'
	end

	def contact
	end
end

week_9/ruby_on_rails Tues/timetracking/app/controllers/time_entries_controller.rb
class TimeEntriesController < ApplicationController
	before_action :set_project, only: [:update, :edit, :create, :index, :new, :destroy]

	def destroy
		flash[:success] = "Time Entry Deleted!"
		@time_entry = @project.time_entries.find(params[:id])
		
		@time_entry.destroy
			redirect_to project_time_entries_path(@project)
		
	end



	def update
			# input: project_id, time_entry id
		# @project = Project.find(params[:project_id])
		@time_entry = @project.time_entries.find(params[:id])
			if @time_entry.update(time_entry_params)
				redirect_to project_time_entries_path(@project)
			else
				render 'edit'
			end
	end


	def edit
		# @project = Project.find(params[:project_id])
		@time_entry = @project.time_entries.find(params[:id])
	end

	def create
			#input: params[:project_id] and params[:time_entry]
			#find resources needed
		# @project = Project.find(params[:project_id])
			# create strong parameters whitelist
		# time_entry_params = params.require(:time_entry).permit(:hours, :minute, :date) - used in the private
			# time_entry_params = {hours,: 1, minutes: 3, date: somedate}
		@time_entry = @project.time_entries.new(time_entry_params)
		if @time_entry.save
			# redirect_to action: 'index', controller: 'time_entries', project_id: @project.id 
			redirect_to project_time_entries_path(@project), notice: "Time Entry Created Successfully"
		else
			render 'new'
		end
	end

	def index
		# @project = Project.find(params[:project_id])
		@time_entries = @project.time_entries
	end

		# def create
		# 	#input: project's id and it'll be in the params hash
		# 	# 1. Find the project
		# 	@project = Project.find(params[:id])

		# 	# 2. Initialize a new time entry for the project
		# 	@time_entry = @project.time_entries.new

		# 	# 3. Save the time eentry

		# 	@time_entry.save

		# 	#...

		# 	#outcome: a time entry for the given project is created
		# end

	def new
		# @project = Project.find(params[:project_id])
		@time_entry = @project.time_entries.new
	end


private

	def set_project
		@project = Project.find(params[:project_id])
	end
	
	def time_entry_params
		params.require(:time_entry).permit(:hours, :minute, :date, :comment)
	end





end

week_9/ruby_on_rails Tues/timetracking/app/helpers/projects_helper.rb
module ProjectsHelper
end

week_9/ruby_on_rails Tues/timetracking/app/helpers/time_entries_helper.rb
module TimeEntriesHelper
end

week_9/ruby_on_rails Tues/timetracking/app/views/time_entries/_form.html.erb
<% if time_entry.errors.any? %>
	<ul>
		<% time_entry.errors.full_messages.each do |error_msg| %>
			<li> <%= error_msg %> </li>
		<%end%>

	</ul>
	<% end %>



<%= form_for [project, time_entry] do |f| %>
	<%= f.label :hours %>
	<%= f.text_field :hours, size: 4 %>
	<br/>
	<%= f.label :minute %>
	<%= f.text_field :minute, size: 4%>
	<br/>
	<%= f.label :date %>
	<%= f.date_field :date %>
	<br/>
	<%= f.label :comments %>
	<%= f.text_area :comments %>
	<br/>

	<%= f.submit 'Save' %>
	<%= link_to 'Cancel', project_time_entries_path(project) %>
<% end %>

week_9/ruby_on_rails Tues/timetracking/app/views/time_entries/edit.html.erb
<%= render partial: "form", locals: {project: @project, time_entry: @time_entry}%>

week_9/ruby_on_rails Tues/timetracking/app/views/time_entries/index.html.erb
<% if flash[:notice] %>
	<%= flash[:notice] %>
	<% end %>
	
<h1> <%= @project.name %></h1>

<h2> <%= flash[:success] %> </h2>

<ol>
	<% @time_entries.each do |time_entry| %>
		<li> 
		<%= time_entry.hours %> h - 
		<%= time_entry.minute %> m -
		<%= time_entry.date %>
		<%= link_to "Edit Time Entry", edit_project_time_entry_path(@project, time_entry) %>
		<%= link_to "Delete", project_time_entry_path(@project, time_entry), method: :delete, data: { confirm: 
			"Are you sure?"} %>
		</li>
	<%end%>
</ol>
		<%= link_to("Projects", projects_path) %>
		<%= link_to("New Time Entry", new_project_time_entry_path(@project)) %>

week_9/ruby_on_rails Tues/timetracking/app/views/time_entries/new.html.erb
<%= render partial: "form", locals: {project: @project, time_entry: @time_entry} %>